### ISSUE TITLE
Tester React/React Native

### ISSUE THREAD

**Issue by na-ji** [BDE-ESIEE/todolist#15]

**Comment by na-ji** [comment]
So @Sangrene ?!

**Comment by mininao** [comment]
Bon du coup moi j'ai testé assez intensivement, c'est stylé. Le gros avantage étant que si une fonctionalité n'es pas dispo on peut écrire du code natif en complément sans problème

**Comment by na-ji** [comment]
Ouai bon moi aussi je fais du React en ce moment et pour l'instant je n'ai
toujours pas fini le "give it five minutes". Donc à voir...
