### ISSUE TITLE
ESIEE Games

### ISSUE THREAD

**Issue by na-ji** [BDE-ESIEE/todolist#19]
- [x] Chaque club a ses propres points
- [ ] Seuil de points
- [ ] Joli design

Reprendre ce qui a été fait pour Poudlard 2.0

**Comment by na-ji** [comment]
@mininao : T'es chaud pour le "Joli Design" ?

**Comment by mininao** [comment]
Ouais ouais, c'est quand la deadline / quand ça commence ?

**Comment by na-ji** [comment]
J'ai fais une milestone juste pour ça : https://github.com/BDE-ESIEE/todolist/milestone/2
Du coup la deadline c'est le 12 septembre. :wink:
